#!/bin/bash
#BSUB -P BIF115
#BSUB -W 0:30
#BSUB -nnodes 1
#BSUB -alloc_flags gpumps
#BSUB -J distr-gnn
#BSUB -o distr-gnn.%J
#BSUB -e distr-gnn.%J

conda activate gnn

hostarr=(${LSB_HOSTS})
echo $LSB_HOSTS
echo ${hostarr[1]}
ddlrun -x WORLD_SIZE=1 -x MASTER_ADDR=${hostarr[1]} -x MASTER_PORT=1234 -accelerators 1 python gcn_distr_2d_gpu.py
