#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=00:10:00
#SBATCH --nodes=1
#SBATCH --gpus=4
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname

# Reddit
srun -l -n 4 --export=ALL,MASTER_ADDR=$hostname --ntasks-per-node=4 --gpus-per-task=1 --gpu-bind=map_gpu:0,1,2,3 python gcn_distr_15d.py --accperrank 1 --epochs 100 --graphname Reddit --timing=True --midlayer 16 --runcount 1 --replication 1 --activations=True &> slurm_outputs/tmp_gcnmaster_reddit_p4c1.out

srun -l -n 4 --export=ALL,MASTER_ADDR=$hostname --ntasks-per-node=4 --gpus-per-task=1 --gpu-bind=map_gpu:0,1,2,3 python gcn_distr_15d.py --accperrank 1 --epochs 100 --graphname Reddit --timing=True --midlayer 16 --runcount 1 --replication 2 --activations=True &> slurm_outputs/tmp_gcnmaster_reddit_p4c2.out
