#!/bin/bash
#BSUB -P BIF115
#BSUB -W 2:00
#BSUB -nnodes 64
#BSUB -alloc_flags gpumps
#BSUB -J distr-gnn2d-p64
#BSUB -o distr-gnn.%J
#BSUB -e distr-gnn.%J

conda activate gnn2

module load cuda
module load gcc

module list

# hostarr=(${LSB_HOSTS})
# echo $LSB_MCPU_HOSTS
hostarr=(${LSB_MCPU_HOSTS})
echo ${hostarr[2]}

# declare -a midlayers=("16" "36" "256")
declare -a midlayers=("16")
declare -a timings=("True" "False")

cd ../../

# Reddit
for i in "${midlayers[@]}"
    do
        for j in "${timings[@]}"
            do
                ddlrun -x WORLD_SIZE=64 -x MASTER_ADDR=${hostarr[2]} -x MASTER_PORT=1234 -accelerators 1 python gcn_distr_2d_gpu_floor.py --accperrank=1 --epochs=100 --graphname=Reddit --timing=$j --midlayer=$i --runcount=1 &> outputs/final_outputs/reddit/distr_proc64_2d_output_mid$i\_$j\_1gpu.txt

            done
    done

# Amazon
for i in "${midlayers[@]}"
    do
        for j in "${timings[@]}"
            do
                ddlrun -x WORLD_SIZE=64 -x MASTER_ADDR=${hostarr[2]} -x MASTER_PORT=1234 -accelerators 1 python gcn_distr_2d_gpu_floor.py --accperrank=1 --epochs=50 --graphname=Amazon --timing=$j --midlayer=$i --runcount=1 &> outputs/final_outputs/amazon/distr_proc64_2d_output_mid$i\_$j\_1gpu.txt

            done
    done

# subgraph3
for i in "${midlayers[@]}"
    do
        for j in "${timings[@]}"
            do
                ddlrun -x WORLD_SIZE=64 -x MASTER_ADDR=${hostarr[2]} -x MASTER_PORT=1234 -accelerators 1 python gcn_distr_2d_gpu_floor.py --accperrank=1 --epochs=10 --graphname=subgraph3 --timing=$j --midlayer=$i --runcount=1 &> outputs/final_outputs/subgraph3/distr_proc64_2d_output_mid$i\_$j\_1gpu.txt

            done
    done
