#!/bin/bash
#BSUB -P BIF115
#BSUB -W 2:00
#BSUB -nnodes 1
#BSUB -alloc_flags gpumps
#BSUB -J distr-gnn-p4
#BSUB -o distr-gnn.%J
#BSUB -e distr-gnn.%J

conda activate gnn2

module load cuda
module load gcc

module list

hostarr=(${LSB_HOSTS})
# echo $LSB_MCPU_HOSTS
# hostarr=(${LSB_MCPU_HOSTS})
echo ${hostarr[2]}

# declare -a midlayers=("16" "64" "256")
declare -a midlayers=("16")
declare -a timings=("True" "False")

cd ../../

# Reddit
for i in "${midlayers[@]}"
    do
        for j in "${timings[@]}"
            do
                ddlrun -x WORLD_SIZE=4 -x MASTER_ADDR=${hostarr[2]} -x MASTER_PORT=1234 -accelerators 4 python gcn_distr_gpu.py --accperrank=4 --epochs=100 --graphname=Reddit --timing=$j --midlayer=$i --runcount=1 &> outputs/final_outputs/reddit/distr_proc4_1d_output_mid$i\_$j\_noop.txt

            done
    done
