#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=02:00:00
#SBATCH --nodes=8
#SBATCH --gpus=32
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname
# Protein_sg2
srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 256 --n-bulkmb 16384 --replication 1 --sample-method ladies --timing --baseline --semibulk 32 --hostname $hostname &> tmp_proteinsg2_ladies_bs256sn256_mb16384_p32c1_semibulk32.out

srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 256 --n-bulkmb 16384 --replication 2 --sample-method ladies --timing --baseline --semibulk 32 --hostname $hostname &> tmp_proteinsg2_ladies_bs256sn256_mb16384_p32c2_semibulk32.out

srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 256 --n-bulkmb 16384 --replication 4 --sample-method ladies --timing --baseline --semibulk 32 --hostname $hostname &> tmp_proteinsg2_ladies_bs256sn256_mb16384_p32c4_semibulk32.out
