#!/bin/bash
#SBATCH --qos=debug
#SBATCH --time=00:30:00
#SBATCH --nodes=8
#SBATCH --gpus=32
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname
# Amazon
srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 32768 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb32768_p32c1_csrallred_int_dbg.out

srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 32768 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb32768_p32c2_csrallred_int_dbg.out

srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 32768 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb32768_p32c4_csrallred_int_dbg.out

# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 512 --samp-num 10 --n-bulkmb 256 --replication 1 --sample-method sage --baseline --hostname $hostname &> tmp_amazon_sage_bs512sn10_mb256_p32c1_csrallred_int_nobarrier.out
# 
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 512 --samp-num 10 --n-bulkmb 256 --replication 2 --sample-method sage --baseline --hostname $hostname &> tmp_amazon_sage_bs512sn10_mb256_p32c2_csrallred_int_nobarrier.out
# 
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 512 --samp-num 10 --n-bulkmb 256 --replication 6 --sample-method sage --baseline --hostname $hostname &> tmp_amazon_sage_bs512sn10_mb256_p32c6_csrallred_int_nobarrier.out

# Protein
srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb16384_p32c4_csrallred_int_dbg.out

srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb16384_p32c2_csrallred_int_dbg.out

srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb16384_p32c1_csrallred_int_dbg.out
