#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=02:00:00
#SBATCH --nodes=16
#SBATCH --gpus=64
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname
module load nccl/2.11.4

# Amazon
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 256 --n-bulkmb 55662 --replication 1 --sample-method ladies --timing --hostname $hostname --semibulk 128 &> tmp_amazon_ladies_bs256sn256_mb55662_p64c1_semibulk128.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 256 --n-bulkmb 55662 --replication 2 --sample-method ladies --timing --hostname $hostname --semibulk 128 &> tmp_amazon_ladies_bs256sn256_mb55662_p64c2_semibulk128.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 256 --n-bulkmb 55662 --replication 4 --sample-method ladies --timing --hostname $hostname --semibulk 128 &> tmp_amazon_ladies_bs256sn256_mb55662_p64c4_semibulk128.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 256 --n-bulkmb 55662 --replication 8 --sample-method ladies --timing --hostname $hostname --semibulk 128 &> tmp_amazon_ladies_bs256sn256_mb55662_p64c8_semibulk128.out

# for i in 32768 16384 8192 4096 2048 1024 512 128 64 
#     do
#         srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 256 --n-bulkmb $i --replication 1 --sample-method ladies --timing --hostname $hostname --semibulk 128 &> tmp_amazon_ladies_bs256sn256_mb$i\_p64c1_semibulk128.out
# 
#         srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 256 --n-bulkmb $i --replication 2 --sample-method ladies --timing --hostname $hostname --semibulk 128 &> tmp_amazon_ladies_bs256sn256_mb$i\_p64c2_semibulk128.out
# 
#         srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 256 --n-bulkmb $i --replication 4 --sample-method ladies --timing --hostname $hostname --semibulk 128 &> tmp_amazon_ladies_bs256sn256_mb$i\_p64c4_semibulk128.out
# 
#         srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 256 --n-bulkmb $i --replication 8 --sample-method ladies --timing --hostname $hostname --semibulk 128 &> tmp_amazon_ladies_bs256sn256_mb$i\_p64c8_semibulk128.out
#     done

# Protein
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 256 --n-bulkmb 34162 --replication 4 --sample-method ladies --timing --hostname $hostname --semibulk 64 &> tmp_protein_ladies_bs256sn256_mb34162_p64c4_semibulk64.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 256 --n-bulkmb 34162 --replication 2 --sample-method ladies --timing --hostname $hostname --semibulk 64 &> tmp_protein_ladies_bs256sn256_mb34162_p64c2_semibulk64.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 256 --n-bulkmb 34162 --replication 1 --sample-method ladies --timing --hostname $hostname --semibulk 64 &> tmp_protein_ladies_bs256sn256_mb34162_p64c1_semibulk64.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 256 --n-bulkmb 34162 --replication 8 --sample-method ladies --timing --hostname $hostname --semibulk 64 &> tmp_protein_ladies_bs256sn256_mb34162_p64c8_semibulk64.out

# for i in 32768 16384 8192 4096 2048 1024 512 128 64 
for i in 34162 32768 16384 8192 256 
    do
        # srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 256 --n-bulkmb $i --replication 4 --sample-method ladies --timing --hostname $hostname --semibulk 64 &> tmp_protein_ladies_bs256sn256_mb$i\_p64c4_semibulk64.out

        # srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 256 --n-bulkmb $i --replication 2 --sample-method ladies --timing --hostname $hostname --semibulk 64 &> tmp_protein_ladies_bs256sn256_mb$i\_p64c2_semibulk64.out

        # srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 256 --n-bulkmb $i --replication 1 --sample-method ladies --timing --hostname $hostname --semibulk 64 &> tmp_protein_ladies_bs256sn256_mb$i\_p64c1_semibulk64.out

        srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 256 --n-bulkmb $i --replication 8 --sample-method ladies --timing --hostname $hostname --semibulk 64 &> tmp_protein_ladies_bs256sn256_mb$i\_p64c8_semibulk64.out
    done
