#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=02:00:00
#SBATCH --nodes=32
#SBATCH --gpus=128
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname
module load nccl/2.11.4

# ogbn-papers100M
srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset ogbn-papers100M --batch-size 256 --samp-num 256 --n-bulkmb 4096 --replication 1 --sample-method ladies --timing --semibulk 4 --hostname $hostname &> tmp_papers_ladies_bs256sn256_mb4096_p128c1_semibulk4.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset ogbn-papers100M --batch-size 256 --samp-num 256 --n-bulkmb 4096 --replication 2 --sample-method ladies --timing --semibulk 4 --hostname $hostname &> tmp_papers_ladies_bs256sn256_mb4096_p128c2_semibulk4.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset ogbn-papers100M --batch-size 256 --samp-num 256 --n-bulkmb 4096 --replication 4 --sample-method ladies --timing --semibulk 4 --hostname $hostname &> tmp_papers_ladies_bs256sn256_mb4096_p128c4_semibulk4.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset ogbn-papers100M --batch-size 256 --samp-num 256 --n-bulkmb 4096 --replication 8 --sample-method ladies --timing --semibulk 4 --hostname $hostname &> tmp_papers_ladies_bs256sn256_mb4096_p128c8_semibulk4.out

