#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=02:00:00
#SBATCH --nodes=8
#SBATCH --gpus=32
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname
# Protein_sg2
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb16384_p32c1_noselect_noloops.out

srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb16384_p32c2_noselect_noloops.out

srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb16384_p32c4_noselect_noloops.out
