#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=02:00:00
#SBATCH --nodes=32
#SBATCH --gpus=128
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname
# Amazon
srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p128c1_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p128c2_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p128c4_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 8 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p128c8_noselect_noloops.out

# Protein
srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 8 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p128c8_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p128c4_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p128c2_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p128c1_noselect_noloops.out
