#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=01:00:00
#SBATCH --nodes=8
#SBATCH --gpus=32
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname
# # Reddit
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset reddit --batch-size 256 --samp-num 10 --n-bulkmb 599 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_reddit_sage_bs256sn10_mb599_p32c1_noselect_noloops.out
# 
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset reddit --batch-size 256 --samp-num 10 --n-bulkmb 599 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_reddit_sage_bs256sn10_mb599_p32c2_noselect_noloops.out
# 
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset reddit --batch-size 256 --samp-num 10 --n-bulkmb 599 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_reddit_sage_bs256sn10_mb599_p32c4_noselect_noloops.out

# # Amazon
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p32c1_noselect_noloops.out
# 
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p32c2_noselect_noloops.out
# 
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p32c4_noselect_noloops.out

# Protein
srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p32c4_noselect_noloops_2xdarts.out

# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p32c2_noselect_noloops.out
# 
# srun -l -n 32 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p32c1_noselect_noloops.out
