#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=02:00:00
#SBATCH --nodes=16
#SBATCH --gpus=64
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname
module load nccl/2.11.4

# Amazon
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p64c1_noselect_noloops.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p64c2_noselect_noloops.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p64c4_noselect_noloops.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb 55662 --replication 8 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb55662_p64c8_noselect_noloops.out

# for i in 32768 16384 8192 4096 2048 1024 512 128 64 
#     do
#         srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb $i --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb$i\_p64c1_noselect_noloops.out
# 
#         srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb $i --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb$i\_p64c2_noselect_noloops.out
# 
#         srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb $i --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb$i\_p64c4_noselect_noloops.out
# 
#         srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Amazon --batch-size 256 --samp-num 10 --n-bulkmb $i --replication 8 --sample-method sage --timing --baseline --hostname $hostname &> tmp_amazon_sage_bs256sn10_mb$i\_p64c8_noselect_noloops.out
#     done

# Protein
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 8 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p64c8_noselect_noloops.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p64c4_noselect_noloops.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p64c2_noselect_noloops.out
# 
# srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb 34162 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb34162_p64c1_noselect_noloops.out

# for i in 32768 16384 8192 4096 2048 1024 512 128 64 
for i in 34162 256 128 64 
    do
        srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb $i --replication 8 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb$i\_p64c8_noselect_noloops.out

        srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb $i --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb$i\_p64c4_noselect_noloops.out

        srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb $i --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb$i\_p64c2_noselect_noloops.out

        srun -l -n 64 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein --batch-size 256 --samp-num 10 --n-bulkmb $i --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_protein_sage_bs256sn10_mb$i\_p64c1_noselect_noloops.out
    done
