#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=02:00:00
#SBATCH --nodes=32
#SBATCH --gpus=128
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=gpu
#SBATCH --account=m1982_g

hostname=$(scontrol show hostnames | head -n 1)
echo $hostname
# Protein_sg2
srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb16384_p128c1_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb16384_p128c2_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb16384_p128c4_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 16384 --replication 8 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb16384_p128c8_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 68324 --replication 1 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb68324_p128c1_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 68324 --replication 2 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb68324_p128c2_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 68324 --replication 4 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb68324_p128c4_noselect_noloops.out

srun -l -n 128 --cpus-per-task 32 --ntasks-per-node 4 --gpus-per-node 4 python gcn_15d.py --dataset Protein_sg2 --batch-size 256 --samp-num 10 --n-bulkmb 68324 --replication 8 --sample-method sage --timing --baseline --hostname $hostname &> tmp_proteinsg2_sage_bs256sn10_mb68324_p128c8_noselect_noloops.out
