#!/bin/bash
#BSUB -P BIF115
#BSUB -W 2:00
#BSUB -nnodes 24
#BSUB -alloc_flags gpumps
#BSUB -J distr-gnn-p144
#BSUB -o distr-gnn.%J
#BSUB -e distr-gnn.%J

conda activate gnn

module load cuda
module load gcc

module list

# hostarr=(${LSB_HOSTS})
# echo $LSB_MCPU_HOSTS
hostarr=(${LSB_MCPU_HOSTS})
echo ${hostarr[2]}

# declare -a midlayers=("64" "256")
declare -a midlayers=("256")
declare -a timings=("True" "False")

# Reddit
for i in "${midlayers[@]}"
    do
        for j in "${timings[@]}"
            do
                ddlrun -x WORLD_SIZE=144 -x MASTER_ADDR=${hostarr[2]} -x MASTER_PORT=1234 -accelerators 6 python gcn_distr_2d_gpu_run.py --accperrank=6 --epochs=100 --graphname=Reddit --timing=$j --midlayer=$i &> outputs/final_outputs/reddit/distr_proc144_2d_output_mid$i\_$j\.txt

            done
    done

# Amazon
for i in "${midlayers[@]}"
    do
        for j in "${timings[@]}"
            do
                # ddlrun -x WORLD_SIZE=144 -x MASTER_ADDR=${hostarr[2]} -x MASTER_PORT=1234 -accelerators 6 python gcn_distr_2d_gpu.py --accperrank=6 --epochs=30 --graphname=Amazon --timing=$j --midlayer=$i &> outputs/final_outputs/amazon/distr_proc144_2d_output_mid$i\_$j\.txt
                ddlrun -x WORLD_SIZE=144 -x MASTER_ADDR=${hostarr[2]} -x MASTER_PORT=1234 -accelerators 6 python gcn_distr_2d_gpu_run.py --accperrank=6 --epochs=100 --graphname=Amazon --timing=$j --midlayer=$i &> outputs/final_outputs/amazon/distr_proc144_2d_output_mid$i\_$j\_e100.txt

            done
    done

# subgraph3
for i in "${midlayers[@]}"
    do
        for j in "${timings[@]}"
            do
                ddlrun -x WORLD_SIZE=144 -x MASTER_ADDR=${hostarr[2]} -x MASTER_PORT=1234 -accelerators 6 python gcn_distr_2d_gpu_run.py --accperrank=6 --epochs=10 --graphname=subgraph3 --timing=$j --midlayer=$i &> outputs/final_outputs/subgraph3/distr_proc144_2d_output_mid$i\_$j\.txt

            done
    done
